name: paramedic_app
description: LifeLink Paramedic Console

environment:
  sdk: '^3.11.0'

dependencies:
  flutter:
    sdk: flutter
  http: any
  # NEW: The open-source map libraries for Flutter
  flutter_map: ^6.1.0 
  latlong2: ^0.9.0
  google_fonts: ^8.0.2
  url_launcher: ^6.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/